### ISSUE TITLE
Remove file

### ISSUE THREAD

**Issue by checklist** [ArtsiomSatsuk/Mobile#1]
Please remove the file https://github.com/ArtsiomSatsuk/Mobile/blob/37a70c96adb8a6a380d8d4a4bd578f50690a741c/apk/Checklist_v6.6.1_apkpure.com.apk as it is copyrighted to us and should not be placed online.

**Comment by ArtsiomSatsuk** [comment]
The file "Checklist_v6.6.1_apkpure.com.apk " has been removed

**Comment by checklist** [comment]
The file is still there in previous commits.
